version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/cli-client"
    schedule:
      interval: "monthly"
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "monthly"
