on:
  push:
    branches: [ main ]
  pull_request:

name: CLI Lints

jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo clippy
        run: cargo clippy --release
        working-directory: cli-client

  rustfmt:
    name: Rustfmt Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt
        run: cargo fmt --verbose -- --check
        working-directory: cli-client
